### ISSUE TITLE
In this completion you will have retain cycle

### ISSUE THREAD

**Issue by 0lefirenko** [DOKononov/KingfisherWithSNP#1]
https://github.com/DOKononov/PagingCollectionView/blob/f48b7a4d6dfecdbdf41da8e2b4e48152f8a6ec10/KingfisherWithSNP/MainVC/MainVCViewModel.swift#L30

**Comment by DOKononov** [comment]
@0lefirenko  is that enough to fix the retain cycle?

**Comment by 0lefirenko** [comment]
Yes, because you remove strong reference to self
I noticed that NetworkService.shared is singleton, so probably it will be not a reference cycle, but MainVCViewModel will be captured, so it is also bad case

**Comment by 0lefirenko** [comment]
You can try to remove singleton and pass NetworkService by protocol in ViewModel

**Comment by DOKononov** [comment]
Ok. Thanks for taking time to help me get better. I'm very grateful for this!  🙂
